version: "3"

services:
  broker:
    build:
      context: ./broker-service
      dockerfile: ./broker.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

